name: performance

on:
  workflow_dispatch:
  push:
    paths:
      - "week7/performance_test.js"
      - ".github/workflows/performance.yml"
  pull_request:
    paths:
      - "week7/performance_test.js"
      - ".github/workflows/performance.yml"

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 test
        run: k6 run week7/performance_test.js
